#!/bin/bash
thisdir="$(dirname "${BASH_SOURCE[0]}")"
LD_LIBRARY_PATH=$PWD/nips_madness/ext/gsl/lib:$LD_LIBRARY_PATH \
exec "$thisdir/run.py" "$@"

# Note: Setting os.environ['LD_LIBRARY_PATH'] in Python interpreter
# does not have the same effect.  It has to be done outside the
# process.
